remote_theme: mikearnaldi/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
'@tinyburg/insight on GitHub':
  - 'https://github.com/leonitousconforti/tinyburg/packages/insight'