name: Check
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm codegen
      - name: Check source state
        run: git add packages/*/src && git diff-index --cached HEAD --exit-code packages/*/src

  types:
    name: Types
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm check
      - run: pnpm circular

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm lint

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm test
        env:
          NIMBLEBIT_AUTH_KEY: ${{ secrets.NIMBLEBIT_AUTH_KEY }}

  deploy-archivist:
    name: Deploy Archivist
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build, types, lint, test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@f4c57e650e1dec6665ad5d3af739b67b9d31aab1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          print_deploy_logs: true
          print_build_logs: true
          app_name: archivist

  deploy-authproxy:
    name: Deploy Authproxy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build, types, lint, test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@f4c57e650e1dec6665ad5d3af739b67b9d31aab1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          print_deploy_logs: true
          print_build_logs: true
          app_name: authproxy

  deploy-auto-gold-bits:
    name: Deploy Auto Gold Bits
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build, types, lint, test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@f4c57e650e1dec6665ad5d3af739b67b9d31aab1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          print_deploy_logs: true
          print_build_logs: true
          app_name: auto-gold-bits

  deploy-tinyburg:
    name: Deploy Tinyburg
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build, types, lint, test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@f4c57e650e1dec6665ad5d3af739b67b9d31aab1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          print_deploy_logs: true
          print_build_logs: true
          app_name: tinyburg
